// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: attendance_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from attendance_code.proto</summary>
  public static partial class AttendanceCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for attendance_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AttendanceCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVhdHRlbmRhbmNlX2NvZGUucHJvdG8SA3JwYxoeZ29vZ2xlL3Byb3RvYnVm",
            "L3dyYXBwZXJzLnByb3RvIkgKFEF0dGVuZGFuY2VDb2RlQ3JlYXRlEhUKDW1p",
            "bnV0ZXNUb0xpdmUYASABKAMSCwoDbGF0GAMgASgBEgwKBGxvbmcYBCABKAEi",
            "RwoOQXR0ZW5kYW5jZUNvZGUSDAoEY29kZRgBIAEoAxIMCgR1bml4GAIgASgD",
            "EgsKA2xhdBgDIAEoARIMCgRsb25nGAQgASgBMqgBChNBdHRlbmRhbmNlQ29k",
            "ZVByb3RvEkkKFUdldEF0dGVuZGFuY2VDb2RlQnlJZBIbLmdvb2dsZS5wcm90",
            "b2J1Zi5JbnQ2NFZhbHVlGhMucnBjLkF0dGVuZGFuY2VDb2RlEkYKFENyZWF0",
            "ZUF0dGVuZGFuY2VDb2RlEhkucnBjLkF0dGVuZGFuY2VDb2RlQ3JlYXRlGhMu",
            "cnBjLkF0dGVuZGFuY2VDb2RlQg9aBC9ycGOqAgZQcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.AttendanceCodeCreate), global::Protos.AttendanceCodeCreate.Parser, new[]{ "MinutesToLive", "Lat", "Long" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.AttendanceCode), global::Protos.AttendanceCode.Parser, new[]{ "Code", "Unix", "Lat", "Long" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AttendanceCodeCreate : pb::IMessage<AttendanceCodeCreate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AttendanceCodeCreate> _parser = new pb::MessageParser<AttendanceCodeCreate>(() => new AttendanceCodeCreate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AttendanceCodeCreate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.AttendanceCodeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttendanceCodeCreate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttendanceCodeCreate(AttendanceCodeCreate other) : this() {
      minutesToLive_ = other.minutesToLive_;
      lat_ = other.lat_;
      long_ = other.long_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttendanceCodeCreate Clone() {
      return new AttendanceCodeCreate(this);
    }

    /// <summary>Field number for the "minutesToLive" field.</summary>
    public const int MinutesToLiveFieldNumber = 1;
    private long minutesToLive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MinutesToLive {
      get { return minutesToLive_; }
      set {
        minutesToLive_ = value;
      }
    }

    /// <summary>Field number for the "lat" field.</summary>
    public const int LatFieldNumber = 3;
    private double lat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Lat {
      get { return lat_; }
      set {
        lat_ = value;
      }
    }

    /// <summary>Field number for the "long" field.</summary>
    public const int LongFieldNumber = 4;
    private double long_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Long {
      get { return long_; }
      set {
        long_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AttendanceCodeCreate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AttendanceCodeCreate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MinutesToLive != other.MinutesToLive) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Lat, other.Lat)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Long, other.Long)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MinutesToLive != 0L) hash ^= MinutesToLive.GetHashCode();
      if (Lat != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Lat);
      if (Long != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Long);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MinutesToLive != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MinutesToLive);
      }
      if (Lat != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Lat);
      }
      if (Long != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Long);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MinutesToLive != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MinutesToLive);
      }
      if (Lat != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Lat);
      }
      if (Long != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Long);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MinutesToLive != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MinutesToLive);
      }
      if (Lat != 0D) {
        size += 1 + 8;
      }
      if (Long != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AttendanceCodeCreate other) {
      if (other == null) {
        return;
      }
      if (other.MinutesToLive != 0L) {
        MinutesToLive = other.MinutesToLive;
      }
      if (other.Lat != 0D) {
        Lat = other.Lat;
      }
      if (other.Long != 0D) {
        Long = other.Long;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MinutesToLive = input.ReadInt64();
            break;
          }
          case 25: {
            Lat = input.ReadDouble();
            break;
          }
          case 33: {
            Long = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MinutesToLive = input.ReadInt64();
            break;
          }
          case 25: {
            Lat = input.ReadDouble();
            break;
          }
          case 33: {
            Long = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AttendanceCode : pb::IMessage<AttendanceCode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AttendanceCode> _parser = new pb::MessageParser<AttendanceCode>(() => new AttendanceCode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AttendanceCode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.AttendanceCodeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttendanceCode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttendanceCode(AttendanceCode other) : this() {
      code_ = other.code_;
      unix_ = other.unix_;
      lat_ = other.lat_;
      long_ = other.long_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttendanceCode Clone() {
      return new AttendanceCode(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private long code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "unix" field.</summary>
    public const int UnixFieldNumber = 2;
    private long unix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unix {
      get { return unix_; }
      set {
        unix_ = value;
      }
    }

    /// <summary>Field number for the "lat" field.</summary>
    public const int LatFieldNumber = 3;
    private double lat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Lat {
      get { return lat_; }
      set {
        lat_ = value;
      }
    }

    /// <summary>Field number for the "long" field.</summary>
    public const int LongFieldNumber = 4;
    private double long_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Long {
      get { return long_; }
      set {
        long_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AttendanceCode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AttendanceCode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Unix != other.Unix) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Lat, other.Lat)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Long, other.Long)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0L) hash ^= Code.GetHashCode();
      if (Unix != 0L) hash ^= Unix.GetHashCode();
      if (Lat != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Lat);
      if (Long != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Long);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Code);
      }
      if (Unix != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Unix);
      }
      if (Lat != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Lat);
      }
      if (Long != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Long);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Code);
      }
      if (Unix != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Unix);
      }
      if (Lat != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Lat);
      }
      if (Long != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Long);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Code);
      }
      if (Unix != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unix);
      }
      if (Lat != 0D) {
        size += 1 + 8;
      }
      if (Long != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AttendanceCode other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0L) {
        Code = other.Code;
      }
      if (other.Unix != 0L) {
        Unix = other.Unix;
      }
      if (other.Lat != 0D) {
        Lat = other.Lat;
      }
      if (other.Long != 0D) {
        Long = other.Long;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt64();
            break;
          }
          case 16: {
            Unix = input.ReadInt64();
            break;
          }
          case 25: {
            Lat = input.ReadDouble();
            break;
          }
          case 33: {
            Long = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt64();
            break;
          }
          case 16: {
            Unix = input.ReadInt64();
            break;
          }
          case 25: {
            Lat = input.ReadDouble();
            break;
          }
          case 33: {
            Long = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
