// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: checkin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from checkin.proto</summary>
  public static partial class CheckinReflection {

    #region Descriptor
    /// <summary>File descriptor for checkin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CheckinReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1jaGVja2luLnByb3RvEgNycGMaHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVy",
            "cy5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvIikKCENoZWNr",
            "SW5zEh0KB2NoZWNrSW4YASADKAsyDC5ycGMuQ2hlY2tJbiJ0CgdDaGVja0lu",
            "EhYKDmF0dGVuZGFuY2VDb2RlGAEgASgDEgoKAmlkGAIgASgDEhEKCXN0dWRl",
            "bnRJZBgDIAEoCRIdCgZzdGF0dXMYBCABKA4yDS5ycGMudmFsaWRpdHkSEwoL",
            "Y2hlY2tpblRpbWUYBSABKAMiMAoMVGltZUludGVydmFsEhAKCGZyb21UaW1l",
            "GAEgASgDEg4KBnRvVGltZRgCIAEoAypeCgh2YWxpZGl0eRIICgROVUxMEAAS",
            "CwoHU1VDQ0VTUxABEg8KC09VVF9PRl9USU1FEAISDQoJTk9UX0ZPVU5EEAMS",
            "EAoMT1VUX09GX1JBTkdFEAQSCQoFRVJST1IQBTKGAwoOQ2hlY2tJblNlcnZp",
            "Y2USOwoOR2V0Q2hlY2tJbkJ5SWQSGy5nb29nbGUucHJvdG9idWYuSW50NjRW",
            "YWx1ZRoMLnJwYy5DaGVja0luEkkKG0dldENoZWNrSW5zQnlBdHRlbmRlbmNl",
            "Q29kZRIbLmdvb2dsZS5wcm90b2J1Zi5JbnQ2NFZhbHVlGg0ucnBjLkNoZWNr",
            "SW5zEkUKFkdldENoZWNrSW5zQnlTdHVkZW50SWQSHC5nb29nbGUucHJvdG9i",
            "dWYuU3RyaW5nVmFsdWUaDS5ycGMuQ2hlY2tJbnMSNQoRR2V0Q2hlY2tJbnNC",
            "eVRpbWUSES5ycGMuVGltZUludGVydmFsGg0ucnBjLkNoZWNrSW5zEjcKDkdl",
            "dEFsbENoZWNrSW5zEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Gg0ucnBjLkNo",
            "ZWNrSW5zEjUKDUluc2VydENoZWNrSW4SDC5ycGMuQ2hlY2tJbhoWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eUIPWgQvcnBjqgIGUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protos.validity), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.CheckIns), global::Protos.CheckIns.Parser, new[]{ "CheckIn" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.CheckIn), global::Protos.CheckIn.Parser, new[]{ "AttendanceCode", "Id", "StudentId", "Status", "CheckinTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.TimeInterval), global::Protos.TimeInterval.Parser, new[]{ "FromTime", "ToTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum validity {
    [pbr::OriginalName("NULL")] Null = 0,
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("OUT_OF_TIME")] OutOfTime = 2,
    [pbr::OriginalName("NOT_FOUND")] NotFound = 3,
    [pbr::OriginalName("OUT_OF_RANGE")] OutOfRange = 4,
    [pbr::OriginalName("ERROR")] Error = 5,
  }

  #endregion

  #region Messages
  public sealed partial class CheckIns : pb::IMessage<CheckIns>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CheckIns> _parser = new pb::MessageParser<CheckIns>(() => new CheckIns());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CheckIns> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.CheckinReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckIns() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckIns(CheckIns other) : this() {
      checkIn_ = other.checkIn_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckIns Clone() {
      return new CheckIns(this);
    }

    /// <summary>Field number for the "checkIn" field.</summary>
    public const int CheckInFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Protos.CheckIn> _repeated_checkIn_codec
        = pb::FieldCodec.ForMessage(10, global::Protos.CheckIn.Parser);
    private readonly pbc::RepeatedField<global::Protos.CheckIn> checkIn_ = new pbc::RepeatedField<global::Protos.CheckIn>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Protos.CheckIn> CheckIn {
      get { return checkIn_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CheckIns);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CheckIns other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!checkIn_.Equals(other.checkIn_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= checkIn_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      checkIn_.WriteTo(output, _repeated_checkIn_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      checkIn_.WriteTo(ref output, _repeated_checkIn_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += checkIn_.CalculateSize(_repeated_checkIn_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CheckIns other) {
      if (other == null) {
        return;
      }
      checkIn_.Add(other.checkIn_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            checkIn_.AddEntriesFrom(input, _repeated_checkIn_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            checkIn_.AddEntriesFrom(ref input, _repeated_checkIn_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CheckIn : pb::IMessage<CheckIn>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CheckIn> _parser = new pb::MessageParser<CheckIn>(() => new CheckIn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CheckIn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.CheckinReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckIn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckIn(CheckIn other) : this() {
      attendanceCode_ = other.attendanceCode_;
      id_ = other.id_;
      studentId_ = other.studentId_;
      status_ = other.status_;
      checkinTime_ = other.checkinTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckIn Clone() {
      return new CheckIn(this);
    }

    /// <summary>Field number for the "attendanceCode" field.</summary>
    public const int AttendanceCodeFieldNumber = 1;
    private long attendanceCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long AttendanceCode {
      get { return attendanceCode_; }
      set {
        attendanceCode_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "studentId" field.</summary>
    public const int StudentIdFieldNumber = 3;
    private string studentId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StudentId {
      get { return studentId_; }
      set {
        studentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 4;
    private global::Protos.validity status_ = global::Protos.validity.Null;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.validity Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "checkinTime" field.</summary>
    public const int CheckinTimeFieldNumber = 5;
    private long checkinTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CheckinTime {
      get { return checkinTime_; }
      set {
        checkinTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CheckIn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CheckIn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AttendanceCode != other.AttendanceCode) return false;
      if (Id != other.Id) return false;
      if (StudentId != other.StudentId) return false;
      if (Status != other.Status) return false;
      if (CheckinTime != other.CheckinTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AttendanceCode != 0L) hash ^= AttendanceCode.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (StudentId.Length != 0) hash ^= StudentId.GetHashCode();
      if (Status != global::Protos.validity.Null) hash ^= Status.GetHashCode();
      if (CheckinTime != 0L) hash ^= CheckinTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AttendanceCode != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AttendanceCode);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (StudentId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StudentId);
      }
      if (Status != global::Protos.validity.Null) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Status);
      }
      if (CheckinTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(CheckinTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AttendanceCode != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AttendanceCode);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (StudentId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StudentId);
      }
      if (Status != global::Protos.validity.Null) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Status);
      }
      if (CheckinTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(CheckinTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AttendanceCode != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AttendanceCode);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (StudentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StudentId);
      }
      if (Status != global::Protos.validity.Null) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (CheckinTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CheckinTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CheckIn other) {
      if (other == null) {
        return;
      }
      if (other.AttendanceCode != 0L) {
        AttendanceCode = other.AttendanceCode;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.StudentId.Length != 0) {
        StudentId = other.StudentId;
      }
      if (other.Status != global::Protos.validity.Null) {
        Status = other.Status;
      }
      if (other.CheckinTime != 0L) {
        CheckinTime = other.CheckinTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AttendanceCode = input.ReadInt64();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
          case 26: {
            StudentId = input.ReadString();
            break;
          }
          case 32: {
            Status = (global::Protos.validity) input.ReadEnum();
            break;
          }
          case 40: {
            CheckinTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AttendanceCode = input.ReadInt64();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
          case 26: {
            StudentId = input.ReadString();
            break;
          }
          case 32: {
            Status = (global::Protos.validity) input.ReadEnum();
            break;
          }
          case 40: {
            CheckinTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TimeInterval : pb::IMessage<TimeInterval>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TimeInterval> _parser = new pb::MessageParser<TimeInterval>(() => new TimeInterval());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TimeInterval> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.CheckinReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TimeInterval() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TimeInterval(TimeInterval other) : this() {
      fromTime_ = other.fromTime_;
      toTime_ = other.toTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TimeInterval Clone() {
      return new TimeInterval(this);
    }

    /// <summary>Field number for the "fromTime" field.</summary>
    public const int FromTimeFieldNumber = 1;
    private long fromTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long FromTime {
      get { return fromTime_; }
      set {
        fromTime_ = value;
      }
    }

    /// <summary>Field number for the "toTime" field.</summary>
    public const int ToTimeFieldNumber = 2;
    private long toTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ToTime {
      get { return toTime_; }
      set {
        toTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TimeInterval);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TimeInterval other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromTime != other.FromTime) return false;
      if (ToTime != other.ToTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FromTime != 0L) hash ^= FromTime.GetHashCode();
      if (ToTime != 0L) hash ^= ToTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FromTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(FromTime);
      }
      if (ToTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ToTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FromTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(FromTime);
      }
      if (ToTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ToTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FromTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FromTime);
      }
      if (ToTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ToTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TimeInterval other) {
      if (other == null) {
        return;
      }
      if (other.FromTime != 0L) {
        FromTime = other.FromTime;
      }
      if (other.ToTime != 0L) {
        ToTime = other.ToTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FromTime = input.ReadInt64();
            break;
          }
          case 16: {
            ToTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FromTime = input.ReadInt64();
            break;
          }
          case 16: {
            ToTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
