// Code generated by protoc-gen-go. DO NOT EDIT.
// source: photo.proto

package photo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Photos struct {
	Photos               []*Photo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Photos) Reset()         { *m = Photos{} }
func (m *Photos) String() string { return proto.CompactTextString(m) }
func (*Photos) ProtoMessage()    {}
func (*Photos) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d481429c0c8c32c, []int{0}
}

func (m *Photos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photos.Unmarshal(m, b)
}
func (m *Photos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photos.Marshal(b, m, deterministic)
}
func (m *Photos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photos.Merge(m, src)
}
func (m *Photos) XXX_Size() int {
	return xxx_messageInfo_Photos.Size(m)
}
func (m *Photos) XXX_DiscardUnknown() {
	xxx_messageInfo_Photos.DiscardUnknown(m)
}

var xxx_messageInfo_Photos proto.InternalMessageInfo

func (m *Photos) GetPhotos() []*Photo {
	if m != nil {
		return m.Photos
	}
	return nil
}

type Photo struct {
	AlbumId              int32    `protobuf:"varint,1,opt,name=albumId,proto3" json:"albumId,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d481429c0c8c32c, []int{1}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetAlbumId() int32 {
	if m != nil {
		return m.AlbumId
	}
	return 0
}

func (m *Photo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Photo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Photo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Photos)(nil), "photo.Photos")
	proto.RegisterType((*Photo)(nil), "photo.Photo")
}

func init() {
	proto.RegisterFile("photo.proto", fileDescriptor_0d481429c0c8c32c)
}

var fileDescriptor_0d481429c0c8c32c = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x89, 0x89, 0x74, 0x5a, 0x45, 0x06, 0x91, 0x25, 0x05, 0x09, 0xc5, 0x43, 0x4e, 0x5b,
	0x48, 0xf1, 0xe0, 0xd1, 0x82, 0x48, 0x6e, 0x25, 0x07, 0xc1, 0x63, 0x42, 0xd6, 0x1a, 0xd8, 0xba,
	0xcb, 0x7e, 0x20, 0xbd, 0xf8, 0x83, 0xfc, 0x95, 0x92, 0xd9, 0x16, 0xd4, 0xde, 0xf6, 0xbd, 0x37,
	0xef, 0xcd, 0xbe, 0x81, 0xa9, 0x7e, 0x57, 0x4e, 0x71, 0x6d, 0x94, 0x53, 0x98, 0x12, 0xc8, 0x6f,
	0xb7, 0x4a, 0x6d, 0xa5, 0x58, 0x12, 0xd9, 0xf9, 0xb7, 0xe5, 0xa7, 0x69, 0xb5, 0x16, 0xc6, 0x86,
	0xb1, 0x7c, 0xfe, 0x5f, 0x17, 0x3b, 0xed, 0xf6, 0x41, 0x5c, 0x70, 0xc8, 0x36, 0x63, 0x8a, 0xc5,
	0x3b, 0xc8, 0x28, 0xcf, 0xb2, 0xa8, 0x48, 0xca, 0x69, 0x35, 0xe3, 0x61, 0x17, 0xc9, 0xcd, 0x41,
	0x5b, 0xbc, 0x42, 0x4a, 0x04, 0x32, 0x38, 0x6f, 0x65, 0xe7, 0x77, 0x75, 0xcf, 0xa2, 0x22, 0x2a,
	0xd3, 0xe6, 0x08, 0xf1, 0x12, 0xe2, 0xa1, 0x67, 0x31, 0x91, 0xf1, 0xd0, 0xe3, 0x35, 0xa4, 0x6e,
	0x70, 0x52, 0xb0, 0xa4, 0x88, 0xca, 0x49, 0x13, 0x00, 0x5e, 0x41, 0xe2, 0x8d, 0x64, 0x67, 0xc4,
	0x8d, 0xcf, 0xea, 0x0b, 0x80, 0xa2, 0x37, 0x54, 0xee, 0x01, 0x66, 0xcf, 0xc2, 0x11, 0xb1, 0xde,
	0xd7, 0x3d, 0xce, 0x79, 0xa8, 0xc1, 0x8f, 0x35, 0x78, 0xfd, 0xe1, 0x56, 0xd5, 0x4b, 0x2b, 0xbd,
	0xc8, 0xff, 0xfc, 0x15, 0xef, 0xc9, 0xfa, 0x28, 0xe5, 0xa1, 0xd9, 0xcd, 0x89, 0xf5, 0x69, 0xbc,
	0x40, 0x7e, 0xf1, 0xdb, 0x65, 0xd7, 0x93, 0xef, 0x38, 0xa3, 0xdd, 0xb6, 0xcb, 0x68, 0x72, 0xf5,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x60, 0x54, 0xd6, 0x6f, 0x01, 0x00, 0x00,
}
