// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attendance_code.proto

package attendancecode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttendanceCodeCreate struct {
	MinutesToLive        int64    `protobuf:"varint,1,opt,name=minutesToLive,proto3" json:"minutesToLive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttendanceCodeCreate) Reset()         { *m = AttendanceCodeCreate{} }
func (m *AttendanceCodeCreate) String() string { return proto.CompactTextString(m) }
func (*AttendanceCodeCreate) ProtoMessage()    {}
func (*AttendanceCodeCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_afd17f95304ceece, []int{0}
}

func (m *AttendanceCodeCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttendanceCodeCreate.Unmarshal(m, b)
}
func (m *AttendanceCodeCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttendanceCodeCreate.Marshal(b, m, deterministic)
}
func (m *AttendanceCodeCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttendanceCodeCreate.Merge(m, src)
}
func (m *AttendanceCodeCreate) XXX_Size() int {
	return xxx_messageInfo_AttendanceCodeCreate.Size(m)
}
func (m *AttendanceCodeCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_AttendanceCodeCreate.DiscardUnknown(m)
}

var xxx_messageInfo_AttendanceCodeCreate proto.InternalMessageInfo

func (m *AttendanceCodeCreate) GetMinutesToLive() int64 {
	if m != nil {
		return m.MinutesToLive
	}
	return 0
}

type AttendanceCode struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Unix                 int64    `protobuf:"varint,2,opt,name=unix,proto3" json:"unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttendanceCode) Reset()         { *m = AttendanceCode{} }
func (m *AttendanceCode) String() string { return proto.CompactTextString(m) }
func (*AttendanceCode) ProtoMessage()    {}
func (*AttendanceCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_afd17f95304ceece, []int{1}
}

func (m *AttendanceCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttendanceCode.Unmarshal(m, b)
}
func (m *AttendanceCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttendanceCode.Marshal(b, m, deterministic)
}
func (m *AttendanceCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttendanceCode.Merge(m, src)
}
func (m *AttendanceCode) XXX_Size() int {
	return xxx_messageInfo_AttendanceCode.Size(m)
}
func (m *AttendanceCode) XXX_DiscardUnknown() {
	xxx_messageInfo_AttendanceCode.DiscardUnknown(m)
}

var xxx_messageInfo_AttendanceCode proto.InternalMessageInfo

func (m *AttendanceCode) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AttendanceCode) GetUnix() int64 {
	if m != nil {
		return m.Unix
	}
	return 0
}

func init() {
	proto.RegisterType((*AttendanceCodeCreate)(nil), "attendancecode.AttendanceCodeCreate")
	proto.RegisterType((*AttendanceCode)(nil), "attendancecode.AttendanceCode")
}

func init() {
	proto.RegisterFile("attendance_code.proto", fileDescriptor_afd17f95304ceece)
}

var fileDescriptor_afd17f95304ceece = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0x29, 0x49,
	0xcd, 0x4b, 0x49, 0xcc, 0x4b, 0x4e, 0x8d, 0x4f, 0xce, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x43, 0x08, 0x83, 0x44, 0xa5, 0xe4, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5,
	0xc1, 0xb2, 0x49, 0xa5, 0x69, 0xfa, 0xe5, 0x45, 0x89, 0x05, 0x05, 0xa9, 0x45, 0xc5, 0x10, 0xf5,
	0x4a, 0x36, 0x5c, 0x22, 0x8e, 0x70, 0x1d, 0xce, 0xf9, 0x29, 0xa9, 0xce, 0x45, 0xa9, 0x89, 0x25,
	0xa9, 0x42, 0x2a, 0x5c, 0xbc, 0xb9, 0x99, 0x79, 0xa5, 0x25, 0xa9, 0xc5, 0x21, 0xf9, 0x3e, 0x99,
	0x65, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0xa8, 0x82, 0x4a, 0x16, 0x5c, 0x7c, 0xa8,
	0xba, 0x85, 0x84, 0xb8, 0x58, 0x40, 0xf6, 0x42, 0x95, 0x83, 0xd9, 0x20, 0xb1, 0xd2, 0xbc, 0xcc,
	0x0a, 0x09, 0x26, 0x88, 0x18, 0x88, 0x6d, 0x74, 0x94, 0x91, 0x4b, 0x18, 0x55, 0x6b, 0x00, 0xd8,
	0xfd, 0x01, 0x5c, 0x82, 0xee, 0xa9, 0x25, 0x68, 0x86, 0x4a, 0xeb, 0x41, 0x7c, 0xa1, 0x07, 0xf3,
	0x85, 0x9e, 0x67, 0x5e, 0x89, 0x99, 0x49, 0x58, 0x62, 0x4e, 0x69, 0xaa, 0x94, 0x9c, 0x1e, 0xaa,
	0x97, 0xf5, 0xd0, 0x34, 0xc7, 0x70, 0x89, 0x40, 0xfc, 0x84, 0x26, 0xae, 0x82, 0x5f, 0x1f, 0x44,
	0x0f, 0x21, 0xd3, 0x9d, 0x38, 0x57, 0x31, 0xb1, 0x81, 0x5d, 0x5e, 0x9c, 0xc4, 0x06, 0x76, 0x9d,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xf9, 0x01, 0xe8, 0x9a, 0x01, 0x00, 0x00,
}
