// Code generated by entc, DO NOT EDIT.

package checkin

const (
	// Label holds the string label denoting the checkin type in the database.
	Label = "check_in"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAttendanceCode holds the string denoting the attendancecode field in the database.
	FieldAttendanceCode = "attendance_code"
	// FieldStudentId holds the string denoting the studentid field in the database.
	FieldStudentId = "student_id"
	// Table holds the table name of the checkin in the database.
	Table = "check_ins"
)

// Columns holds all SQL columns for checkin fields.
var Columns = []string{
	FieldID,
	FieldAttendanceCode,
	FieldStudentId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AttendanceCodeValidator is a validator for the "attendanceCode" field. It is called by the builders before save.
	AttendanceCodeValidator func(int64) error
)
