import type { NextPage } from 'next'
import Head from 'next/head'
import { useSession } from "next-auth/react";
import CodeCreateForm from '../components/codecreate_form'
import Menu from '../components/menu'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Router from 'next/router'

const Teacher: NextPage = () => {
    const { data: session } = useSession()

    if (!session?.user)
        Router.push("/")

    return (
        <div className={styles.container}>
            <Head>
                <title>AA - Teacher Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Menu />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <Link href="/teacher"><a>Teacher</a></Link> page
                </h1>

                <p className={styles.description}>
                    Logged in as{' '}
                    <code className={styles.code}>{session?.user?.name}</code>
                </p>

                <div className={styles.table}>
                    <CodeCreateForm />
                </div>
            </main>
        </div>
    )
}

export default Teacher
