name: "main_images_build"

on:
  push:
    branches:
      - main

jobs:
  call-workflow-build-push-service-photos-image:
    name: Build and Push service photos Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: service_photos
      image_path: "applications/service_photos"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
  
  call-workflow-build-push-api-image:
    name: Build and Push api Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: api
      image_path: "applications/api"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}