name: "main_images_build"

on:
  push:
    branches:
      - main

jobs: 
  call-workflow-build-push-api-image:
    name: Build and Push api service Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: api_service
      image_path: "applications/services/api"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

  call-workflow-build-push-redis-service:
    name: Build and Push redis service Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: redis_service
      image_path: "applications/services/redis"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

  call-workflow-build-push-postgres-service:
    name: Build and Push postgres service Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: postgres_service
      image_path: "applications/services/postgres"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

  call-workflow-build-push-frontend-service:
    name: Build and Push frontend service Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: frontend_service
      image_path: "applications/services/frontend"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}