name: "main_images_build"

on:
  push:
    branches:
      - main

jobs:
  call-workflow-build-push-test1-image:
    name: Build and Push test1 Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: test1
      image_path: "applications/test1"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
  
  call-workflow-build-push-api-image:
    name: Build and Push api Docker Image
    uses: andreasvikke/CPH-Business-LS-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: api
      image_path: "applications/api"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}